# Generated by Django 2.1.5 on 2019-01-28 22:06

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('thumbnail', models.ImageField(height_field=1000, max_length=3100000, upload_to='', width_field=1000)),
                ('title', models.CharField(max_length=127)),
                ('description', models.CharField(max_length=1023)),
                ('price', models.FloatField(db_index=True, validators=[products.models.product.price_check])),
                ('valuta', models.CharField(choices=[('Dollars', 'USD'), ('Euro', 'EUR'), ('Bitcoin', 'BTC')], max_length=3)),
                ('rating', models.FloatField(db_index=True, null=True, validators=[products.models.product.rating_check])),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(height_field=1000, max_length=3100000, upload_to='', width_field=1000)),
                ('rating', models.FloatField(db_index=True, validators=[products.models.seller.rating_check])),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='venditore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.seller'),
        ),
    ]
